### ISSUE TITLE
new forge release to allow compatibility with puppet/archive 6.x

### ISSUE THREAD

**Issue by jhoblitt** [puppetlabs/puppetlabs-tomcat#487]
`metadata.json` on current `master` has changes which are need to allow `puppet/archive` 6.x to be used within a puppet environment.  This issue is requesting that a new forge release be made from the current `master`.

**Comment by chelnak** [comment]
Hey! Please can you add a bit more detail to this issue? It might be useful to use one of the templates we have [here](https://github.com/puppetlabs/puppetlabs-tomcat/issues/new/choose)!

Thank you!

**Comment by jhoblitt** [comment]
I have updated the issue description.

**Comment by chelnak** [comment]
Thank you!

**Comment by petergmurphy** [comment]
This issue has been resolved with the latest release (`6.2.0`) of this module.
