### ISSUE TITLE
Tomcat module declares Puppet 8 compatibility, but its dependency modules do not

### ISSUE THREAD

**Issue by PuppetNPC** [puppetlabs/puppetlabs-tomcat#555]
## Describe the Bug

The puppetlabs-tomcat module states it has Puppet 8 compatibility, however it has a dependency upon a version of the puppet-archive module which doesn't support Puppet 8. Currently puppetlabs-tomcat 7.1.0 requires a version of puppet-archive >= 1.0.0 < 7.0.0. However puppet-archive is not Puppet 8 compatible until version 7.1.0, which is outside of the puppet-tomcat dependency range.

**Comment by h-haaks** [comment]
This seems to have been solved by 4779f06 6 month ago, but no new release to forge ...
Seems like there is some serious problems in the actions setup that prevents new releases of this module.

**Comment by h-haaks** [comment]
#554 is held back because nightly builds have not succeeded in a month

**Comment by Ramesh7** [comment]
Have released new version of tomcat `v7.2.0` (https://github.com/puppetlabs/puppetlabs-tomcat/pull/554), Hence closing this.
