### ISSUE TITLE
The additional_attributes hash for tomcat::config::server::connector has been removed. It should be present.

### ISSUE THREAD

**Issue by cvquesty** [puppetlabs/puppetlabs-tomcat#565]
## Describe the Bug
For the defined type tomncat::config::server::connector, the parameter additional_attributes has been removed entirely without documentation or explanation with no alternative methods provided to utilize the sane functionality.

## Expected Behavior
additional_attributes should be present in the above context.  This is in use across several client fleets, and this introduces a BREAKING CHANGE.  Also, the removal of this is not reflected in the documentation.

## Steps to Reproduce
This is a code issue introduced in a commit by @Joris29 last year. If the intent was to remove the functionality, the documentation should be updated to reflect the code chanbge. If the additional_attributes hash was NOT intended to be removed, it should be reintroduced to match the existing documentation.

## Environment
Any platform using tomcat module

## Additional Context
This is a breakinbg change without appropriate documentation

**Comment by Joris29** [comment]
Hello @cvquesty not sure what's going wrong for you but this parameter is most certainly not removed.

**Comment by cvquesty** [comment]
It looks like the edit fooled me.  The hash was removed and added (the way Git looks at things), but the module is most definitely reporting that the param does not exist.  

I’ve put this up in its entirety on forge-modules for some visibility.  This code has been in place in our environment for almost 4 years.  The change is the update to the tomcat module to the most current.

Jerald Sheets
***@***.***
